#!/usr/bin/with-contenv sh

# Launch Wireguard
wg-quick up /etc/wireguard/wg0.conf 1>/tmp/wg0.up 2>&1
sleep 5

# Extract endpoint
LOCAL_EP=`wg show wg0 endpoints | sed 's/^.*\s//' | cut -d\: -f1`

# Loop, exit if connection lost
exec env LOCAL_EP=$LOCAL_EP sh -c 'while(true); do ping -c4 $LOCAL_EP 1>/tmp/wg0.ping 2>&1; if [ "$?" != "0" ]; then wg-quick down wg0; date > /tmp/wg0.died; exit 1; fi; sleep 15; done'

