name: Docker Build and Publish

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alpine-wireguard:$(date +%s)
