name: Docker Image CI

on:
   push:
    branches: ['release']
   pull_request:
    branches: ['release']
   
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alpine-wireguard:$(date +%s)
