name: Docker Image CI

on:
   schedule:
    - cron: "1 16 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alpine-wireguard:$(date +%s)
